describe('test elements assertions', () => {

    beforeEach(() => {
        cy.viewport(1920,1080)
        cy.visit('https://docs.nativebase.io')
    })

const menuList = [
'Getting Started',
'Installation',
'Setup NativeBase Provider',
// 'Resources',
'Contribution',
'Creating a Universal App with NativeBase and SolitoNew',
// 'Core Concepts',
'Utility First',
'Utility Props Specificity',
'Design Tokens',
'Pseudo Props',
"Pseudo Props: Dos & Don'ts",
'Internal Pseudo PropsNew',
'Responsive',
'Utility Props',
'Color mode (Dark Mode)',
'NativeBase Factory',
'SafeAreaView Props',
'Strict Mode',
'Accessibility',
'Theme',
'Customizing Theme',
'Customizing Fonts',
'Customizing Components',
'Making components dark mode compatible',
'Breakpoints',
'Using Theme',
'TypeScript',
'AspectRatio',
'Box',
'Center',
'Container',
'Flex',
'HStack / Row',
'Stack',
'VStack / Column',
'ZStack',
'Button',
'Pressable',
'Checkbox',
'FormControl',
'IconButton',
'Input',
'Link',
'Radio',
'Select',
'Slider',
'Switch',
'TextArea',
'Badge',
'Divider',
'Alert',
'Progress',
'Skeleton',
'Spinner',
'ToastUpdate',
// 'Typography',
'Text',
'Heading',
// 'Overlay',
'AlertDialog',
'Menu',
'Modal',
'Popover',
'Tooltip',
// 'Disclosure',
'ActionSheet',
// 'Media and Icons',
'Avatar',
'Icon',
'Image',
// 'Transition',
'PresenceTransition',
'Slide',
'Stagger',
// 'Others',
'Fab',
'Hidden',
// 'ReactNative Components',
'ScrollView',
'View',
'KeyboardAvoidingView',
'StatusBar',
'FlatList',
'SectionList',
// 'Hooks',
'useDisclose',
'useBreakpointValue',
'useClipboard',
'useMediaQuery',
'useTheme',
'useToken',
'useColorMode',
'useColorModeValue',
'useContrastText',
'useAccessibleColors',
// 'Examples',
'Todo-List',
'Kitchen Sink',  
// 'Recipes',
// 'Designs',
'AppBar',
'Card',
'Drawer Navigation',    
'Tab View',
'Swipe List', 
// 'Forms',
'Form with Validation',
'Login/Signup Forms',
'SearchBar',
// 'Layout',
'App Drawer',
'Footer',
// 'Migration',             
'Upgrading to v3',
'Upgrading to 3.2.0 from 3.x',
'Upgrading to 3.4.0 from 3.3.x',
//Components Migration
'ActionSheet',
'Badge',
'Button',
'Card',
'Checkbox',
'DatePicker',
'DeckSwiper',
'Drawer',
'FABs',
'FooterTab',
'Form',
'Header',
'Icon',
'Layout',
'Picker',
'Radio Button',    
'Searchbar',
'Segment',
'Spinner',         
'SwipeList',
'Tabs',
'Thumbnail',
'Toast',
'Typography',
// 'More',
'Changelog',
'Testing',
"FAQ's",
"More Props"
]
    it("checks all the Menu Items", () =>{ 
        cy.xpath("//div[@class='css-1dbjc4n r-1niwhzg r-1loqt21 r-1otgn73']").as("MenuList")
        cy.get('@MenuList').each((item,index,list) => {
            cy.wrap(item).should('contain.text',menuList[index])
        })

        })
})