module.exports = {
  componentsSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      collapsed: false,
      items: ['nativebase', 'installation', 'setup-provider'],
    },
    {
      type: 'category',
      label: 'Features',
      collapsed: false,
      items: [
        'color-mode',
        'nativebase-factory',
        'responsive-style',
        'safe-area-view-props',
      ],
    },
    {
      type: 'category',
      label: 'Theme',
      collapsed: false,
      items: [
        'default-theme',
        'customizingTheme',
        'darkMode',
        'customizingComponents',
        'breakpoint',
        'theme',
      ],
    },
    {
      type: 'category',
      label: 'Layout',
      collapsed: false,
      items: [
        'aspectRatio',
        'box',
        'center',
        'Column',
        'container',
        'flex',
        'hStack',
        'row',
        'simpleGrid',
        'stack',
        'view',
        'VStack',
        'wrap',
        'ZStack',
      ],
    },
    {
      type: 'category',
      label: 'Forms',
      collapsed: false,
      items: [
        'button',
        'checkBox',
        'formControl',
        'iconButton',
        'input',
        'numberInput',
        'link',
        'pinInput',
        'radio',
        'select',
        'slider',
        'switch',
        'textArea',
        'typeAhead',
      ],
    },
    {
      type: 'category',
      label: 'Data Display',
      collapsed: false,
      items: [
        'badge',
        'closeButton',
        'code',
        'divider',
        'Kbd',
        'list',
        'stat',
        'tag',
      ],
    },
    {
      type: 'category',
      label: 'Feedback',
      collapsed: false,
      items: [
        'alert',
        'circularProgress',
        'progress',
        'skeleton',
        'snackBar',
        'spinner',
        'toast',
      ],
    },
    {
      type: 'category',
      label: 'Typography',
      collapsed: false,
      items: ['text', 'heading'],
    },
    {
      type: 'category',
      label: 'Overlay',
      collapsed: false,
      items: ['alertDialog', 'menu', 'modal', 'overlay', 'popOver'],
    },
    {
      type: 'category',
      label: 'Disclosure',
      collapsed: false,
      items: ['accordion', 'actionSheet', 'breadcrumb', 'collapse', 'tabs'],
    },
    {
      type: 'category',
      label: 'Media and Icons',
      collapsed: false,
      items: ['avatar', 'icon', 'image'],
    },
    {
      type: 'category',
      label: 'Others',
      collapsed: false,
      items: ['appBar', 'FAB', 'transition'],
    },
    {
      type: 'category',
      label: 'Hooks',
      collapsed: false,
      items: [
        'use-disclosure',
        'use-popOver',
        'use-breakPoint-value',
        'use-clipboard',
        'use-media-query',
        'use-theme',
        'use-token',
        'use-color-mode',
        'use-color-mode-value',
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      collapsed: false,
      items: ['todo-example'],
    },
    {
      type: 'category',
      label: 'Community Integration',
      collapsed: false,
      items: ['react-hook-forms', 'nativebase-formik-ui'],
    },
    {
      type: 'category',
      label: 'Recipes',
      collapsed: false,
      items: [
        {
          Designs: ['buildingCard', 'buildingSearchBar'],
          Forms: ['form'],
          Layout: ['appDrawer'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Migration',
      collapsed: false,
      items: [
        {
          Components: [
            'migration/Accordion',
            'migration/Actionsheet',
            'migration/Badge',
            'migration/Button',
            'migration/Card',
            'migration/Checkbox',
            'migration/FABs',
            'migration/Footer Tab',
            'migration/Header',
            'migration/Icon',
            'migration/Layout',
            'migration/Picker',
            'migration/Radio Button',
            'migration/Searchbar',
            'migration/Spinner',
            'migration/Tabs',
            'migration/Thumbnail',
            'migration/Toast',
            'migration/Typography',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'More',
      collapsed: false,
      items: ['changelog', 'faq'],
    },
  ],
};
