module.exports = {
  someSidebar: {
    // Introduction: ["nativebase", "installation", "setup-provider"],
    // Example: ["todo-example"],
    // Features: ["color-mode", "nativebase-factory", "responsive-style"],
    // "Community Integrations": ["nativebase-formik-ui", "react-hook-forms"],
    // Layout: [
    //   "aspect-ratio",
    //   "box",
    //   "center",
    //   "column",
    //   "container",
    //   "flex",
    //   "hstack",
    //   "row",
    //   "simple-grid",
    //   "stack",
    //   "view",
    //   "vstack",
    //   "wrap",
    //   "zstack",
    // ],
    // Forms: [
    //   "button",
    //   "checkbox",
    //   "form-control",
    //   "icon-button",
    //   "input",
    //   "number-input",
    //   "link",
    //   "pin-input",
    //   "radio",
    //   "select",
    //   "slider",
    //   "switch",
    //   "text-area",
    //   "typeahead",
    // ],
    // "Data Display": [
    //   "badge",
    //   "close-button",
    //   "code",
    //   "divider",
    //   "kbd",
    //   "list",
    //   "stat",
    //   "tag",
    // ],
    // Feedback: [
    //   "alert",
    //   "circular-progress",
    //   "progress",
    //   "skeleton",
    //   "snackbar",
    //   "spinner",
    //   "toast",
    // ],
    // Typography: ["heading", "text"],
    // Overlay: ["alert-dialog", "menu", "modal", "overlay", "popover"],
    // Disclosure: ["accordion", "actionsheet", "bread-crumb", "collapse", "tab"],
    // "Media and Icons": ["avatar", "icon", "image"],
    // Others: ["app-bar", "fab", "transition"],
    // Hooks: [
    //   "use-breakpoint-value",
    //   "use-clipboard",
    //   "use-disclose",
    //   "use-media-query",
    //   "use-popover",
    //   "use-theme",
    //   "use-token",
    // ],
    // Theming: ["default-theme", "customizing-theme"],
    // FAQ: ["faq"],
    Test: [
      "accordion",
      "actionSheet",
      "alert",
      "alertDialog",
      "appBar",
      "aspectRatio",
      "avatar",
      "badge",
      "box",
      "breadCrumb",
      "button",
      "center",
      "checkBox",
      "circularProgress",
      "closeButton",
      "code",
      "collapse",
      "columns",
      "container",
      "divider",
      "FAB",
      "flex",
      "formControl",
      "heading",
      "hook",
      "hStack",
      "icon",
      "iconButton",
      "image",
      "input",
      "Kbd",
      "link",
      "list",
      "menu",
      "modal",
      "numberInput",
      "overlay",
      "pinInput",
      "popOver",
      "progress",
      "radio",
      "row",
      "simpleGrid",
      "skeleton",
      "slider",
      "snackBar",
      "spinner",
      "select",
      "stack",
      "stat",
      "switch",
      "tab",
      "tag",
      "text",
      "textArea",
      "toast",
      "transition",
      "typeAhead",
      "view",
      "VStack",
      "wrap",
      "ZStack",
    ],
  },
};
