module.exports = {
	componentsSidebar: {
		Introduction: ['nativebase', 'installation', 'setup-provider'],
		Features: ['color-mode', 'nativebase-factory', 'responsive-style'],
		Layout: [
			'aspectRatio',
			'box',
			'center',
			'Column',
			'container',
			'flex',
			'hStack',
			'row',
			'simpleGrid',
			'stack',
			'view',
			'VStack',
			'wrap',
			'ZStack',
		],
		Forms: [
			'button',
			'checkBox',
			'formControl',
			'iconButton',
			'input',
			'numberInput',
			'link',
			'pinInput',
			'radio',
			'select',
			'slider',
			'switch',
			'textArea',
			'typeAhead',
		],
		'Data Display': [
			'badge',
			'closeButton',
			'code',
			'divider',
			'Kbd',
			'list',
			'stat',
			'tag',
		],
		Feedback: [
			'alert',
			'circularProgress',
			'progress',
			'skeleton',
			'snackBar',
			'spinner',
			'toast',
		],
		Typography: ['text', 'heading'],
		Overlay: ['alertDialog', 'menu', 'modal', 'overlay', 'popOver'],
		Disclosure: ['accordion', 'actionSheet', 'breadcrumb', 'collapse', 'tab'],
		'Media and Icons': ['avatar', 'icon', 'image'],
		Others: ['appBar', 'FAB', 'transition'],
		Hooks: [
			'use-disclosure',
			'use-popOver',
			'use-breakPoint-value',
			'use-clipboard',
			'use-media-query',
			'use-theme',
			'use-token',
			'use-color-mode',
			'use-color-mode-value',
		],
		Theme: ['default-theme'],
		Examples: ['todo-example'],
		'Community Integration': ['react-hook-forms', 'nativebase-formik-ui'],
		Recipes: [
			{
				Designs: ['buildingCard', 'buildingSearchBar'],
				Forms: ['form'],
				Layout: ['appDrawer'],
				Theme: [
					'customizingTheme',
					'darkMode',
					'customizingComponents',
					'breakpoint',
					'theme',
				],
			},
		],
		Migration: [
			{
				Components: [
					'migration/Accordion',
					'migration/Actionsheet',
					'migration/Badge',
					'migration/Button',
					'migration/Card',
					'migration/Checkbox',
					'migration/FABs',
					'migration/Footer Tab',
					'migration/Header',
					'migration/Icon',
					'migration/Layout',
					'migration/Picker',
					'migration/Radio Button',
					'migration/Searchbar',
					'migration/Spinner',
					'migration/Tabs',
					'migration/Thumbnail',
					'migration/Toast',
					'migration/Typography',
				],
			},
		],
		More: ['changelog', 'faq'],
	},
};
