name: Cypress tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          node-version: 16
          start: npm start
          config-file: test-automation-cypress/cypress.config.js
          spec: test-automation-cypress/cypress/e2e/pom/checkAllVerticalNavigations.spec.js
